"""Initial migration

Revision ID: f475e7e4eb08
Revises: 
Create Date: 2024-10-01 18:34:49.955880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f475e7e4eb08'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('authtoken_token_key_10f0b77e_like', table_name='authtoken_token')
    op.drop_table('authtoken_token')
    op.drop_index('auth_group_name_a6ea08ec_like', table_name='auth_group')
    op.drop_table('auth_group')
    op.drop_table('django_content_type')
    op.drop_index('blogging_app_comment_post_id_72223a2d', table_name='blogging_app_comment')
    op.drop_table('blogging_app_comment')
    op.drop_index('auth_user_user_permissions_permission_id_1fbb5f2c', table_name='auth_user_user_permissions')
    op.drop_index('auth_user_user_permissions_user_id_a95ead1b', table_name='auth_user_user_permissions')
    op.drop_table('auth_user_user_permissions')
    op.drop_table('orders')
    op.drop_index('admin_interface_theme_name_30bda70f_like', table_name='admin_interface_theme')
    op.drop_table('admin_interface_theme')
    op.drop_index('auth_group_permissions_group_id_b120cbf9', table_name='auth_group_permissions')
    op.drop_index('auth_group_permissions_permission_id_84c5c92e', table_name='auth_group_permissions')
    op.drop_table('auth_group_permissions')
    op.drop_table('books')
    op.drop_table('student_app_student')
    op.drop_index('stockApp_transaction_ticker_id_81a0a87b', table_name='stockApp_transaction')
    op.drop_index('stockApp_transaction_user_id_c2d4f553', table_name='stockApp_transaction')
    op.drop_table('stockApp_transaction')
    op.drop_index('auth_permission_content_type_id_2f476e4b', table_name='auth_permission')
    op.drop_table('auth_permission')
    op.drop_table('django_migrations')
    op.drop_table('customer')
    op.drop_index('auth_user_username_6821ab7c_like', table_name='auth_user')
    op.drop_table('auth_user')
    op.drop_index('stockApp_stock_ticker_0eaf1fe1_like', table_name='stockApp_stock')
    op.drop_table('stockApp_stock')
    op.drop_table('cars')
    op.drop_index('django_session_expire_date_a5c62663', table_name='django_session')
    op.drop_index('django_session_session_key_c0390e0f_like', table_name='django_session')
    op.drop_table('django_session')
    op.drop_table('stockApp_user')
    op.drop_table('blogging_app_post')
    op.drop_table('cust')
    op.drop_table('person')
    op.drop_index('auth_user_groups_group_id_97559544', table_name='auth_user_groups')
    op.drop_index('auth_user_groups_user_id_6a12ed8b', table_name='auth_user_groups')
    op.drop_table('auth_user_groups')
    op.drop_table('studentapp_student')
    op.drop_table('customers')
    op.drop_index('django_admin_log_content_type_id_c4bce8eb', table_name='django_admin_log')
    op.drop_index('django_admin_log_user_id_c564eba6', table_name='django_admin_log')
    op.drop_table('django_admin_log')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('django_admin_log',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('action_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('object_repr', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('action_flag', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('change_message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('action_flag >= 0', name='django_admin_log_action_flag_check'),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='django_admin_log_content_type_id_c4bce8eb_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='django_admin_log_user_id_c564eba6_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='django_admin_log_pkey')
    )
    op.create_index('django_admin_log_user_id_c564eba6', 'django_admin_log', ['user_id'], unique=False)
    op.create_index('django_admin_log_content_type_id_c4bce8eb', 'django_admin_log', ['content_type_id'], unique=False)
    op.create_table('customers',
    sa.Column('customer_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('customer_id', name='customers_pkey')
    )
    op.create_table('studentapp_student',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('grade', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='studentapp_student_pkey')
    )
    op.create_table('auth_user_groups',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_user_groups_group_id_97559544_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_groups_user_id_6a12ed8b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_groups_pkey'),
    sa.UniqueConstraint('user_id', 'group_id', name='auth_user_groups_user_id_group_id_94350c0c_uniq')
    )
    op.create_index('auth_user_groups_user_id_6a12ed8b', 'auth_user_groups', ['user_id'], unique=False)
    op.create_index('auth_user_groups_group_id_97559544', 'auth_user_groups', ['group_id'], unique=False)
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='person_pkey')
    )
    op.create_table('cust',
    sa.Column('customer_id', sa.INTEGER(), server_default=sa.text("nextval('cust_customer_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('cutomer_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('customer_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('customer_id', name='cust_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('blogging_app_post',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('published_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='blogging_app_post_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('stockApp_user',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('Initial_balance', sa.NUMERIC(precision=30, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='stockApp_user_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('django_session',
    sa.Column('session_key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('session_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('expire_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('session_key', name='django_session_pkey')
    )
    op.create_index('django_session_session_key_c0390e0f_like', 'django_session', ['session_key'], unique=False)
    op.create_index('django_session_expire_date_a5c62663', 'django_session', ['expire_date'], unique=False)
    op.create_table('cars',
    sa.Column('c_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('c_year', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('stockApp_stock',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='stockApp_stock_pkey'),
    sa.UniqueConstraint('ticker', name='stockApp_stock_ticker_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('stockApp_stock_ticker_0eaf1fe1_like', 'stockApp_stock', ['ticker'], unique=False)
    op.create_table('auth_user',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('last_login', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=254), autoincrement=False, nullable=False),
    sa.Column('is_staff', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('date_joined', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_user_pkey'),
    sa.UniqueConstraint('username', name='auth_user_username_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_user_username_6821ab7c_like', 'auth_user', ['username'], unique=False)
    op.create_table('customer',
    sa.Column('customer_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('c_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint('age > 18', name='customer_age_check'),
    sa.PrimaryKeyConstraint('customer_id', name='customer_pkey')
    )
    op.create_table('django_migrations',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('applied', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_migrations_pkey')
    )
    op.create_table('auth_permission',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('content_type_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth_permission_content_type_id_2f476e4b_fk_django_co', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_permission_pkey'),
    sa.UniqueConstraint('content_type_id', 'codename', name='auth_permission_content_type_id_codename_01ab375a_uniq'),
    postgresql_ignore_search_path=False
    )
    op.create_index('auth_permission_content_type_id_2f476e4b', 'auth_permission', ['content_type_id'], unique=False)
    op.create_table('stockApp_transaction',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('transaction_type', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.Column('transaction_volume', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('transaction_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('ticker_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_id_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.CheckConstraint('transaction_volume >= 0', name='stockApp_transaction_transaction_volume_check'),
    sa.ForeignKeyConstraint(['ticker_id'], ['stockApp_stock.id'], name='stockApp_transaction_ticker_id_81a0a87b_fk_stockApp_stock_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id_id'], ['stockApp_user.id'], name='stockApp_transaction_user_id_id_da4ced08_fk_stockApp_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='stockApp_transaction_pkey')
    )
    op.create_index('stockApp_transaction_user_id_c2d4f553', 'stockApp_transaction', ['user_id_id'], unique=False)
    op.create_index('stockApp_transaction_ticker_id_81a0a87b', 'stockApp_transaction', ['ticker_id'], unique=False)
    op.create_table('student_app_student',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('degree', sa.VARCHAR(length=10), server_default=sa.text("'BA'::character varying"), autoincrement=False, nullable=False),
    sa.CheckConstraint("degree::text = ANY (ARRAY['BA'::character varying, 'MA'::character varying, 'PhD'::character varying]::text[])", name='degree_check'),
    sa.PrimaryKeyConstraint('id', name='student_app_student_pkey')
    )
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='books_pkey')
    )
    op.create_table('auth_group_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_group_permissions_group_id_b120cbf9_fk_auth_group_id', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_group_permissio_permission_id_84c5c92e_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_group_permissions_pkey'),
    sa.UniqueConstraint('group_id', 'permission_id', name='auth_group_permissions_group_id_permission_id_0cd325b0_uniq')
    )
    op.create_index('auth_group_permissions_permission_id_84c5c92e', 'auth_group_permissions', ['permission_id'], unique=False)
    op.create_index('auth_group_permissions_group_id_b120cbf9', 'auth_group_permissions', ['group_id'], unique=False)
    op.create_table('admin_interface_theme',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title_visible', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('logo', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('logo_visible', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('css_header_background_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('title_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('css_header_text_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('css_header_link_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('css_header_link_hover_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('css_module_background_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('css_module_text_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('css_module_link_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('css_module_link_hover_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('css_module_rounded_corners', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('css_generic_link_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('css_generic_link_hover_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('css_save_button_background_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('css_save_button_background_hover_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('css_save_button_text_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('css_delete_button_background_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('css_delete_button_background_hover_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('css_delete_button_text_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('list_filter_dropdown', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('related_modal_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('related_modal_background_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('related_modal_rounded_corners', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('logo_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('recent_actions_visible', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('favicon', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('related_modal_background_opacity', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('env_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('env_visible_in_header', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('env_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('env_visible_in_favicon', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('related_modal_close_button_visible', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('language_chooser_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('language_chooser_display', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('list_filter_sticky', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('form_pagination_sticky', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('form_submit_sticky', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('css_module_background_selected_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('css_module_link_selected_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('logo_max_height', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('logo_max_width', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('foldable_apps', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('language_chooser_control', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('list_filter_highlight', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('list_filter_removal_links', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('show_fieldsets_as_tabs', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('show_inlines_as_tabs', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('css_generic_link_active_color', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('collapsible_stacked_inlines', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('collapsible_stacked_inlines_collapsed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('collapsible_tabular_inlines', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('collapsible_tabular_inlines_collapsed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.CheckConstraint('logo_max_height >= 0', name='admin_interface_theme_logo_max_height_check'),
    sa.CheckConstraint('logo_max_width >= 0', name='admin_interface_theme_logo_max_width_check'),
    sa.PrimaryKeyConstraint('id', name='admin_interface_theme_pkey'),
    sa.UniqueConstraint('name', name='admin_interface_theme_name_30bda70f_uniq')
    )
    op.create_index('admin_interface_theme_name_30bda70f_like', 'admin_interface_theme', ['name'], unique=False)
    op.create_table('orders',
    sa.Column('order_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_no', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('order_description', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('order_date', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=True),
    sa.CheckConstraint('price > 0', name='orders_price_check'),
    sa.ForeignKeyConstraint(['customer_id'], ['cust.customer_id'], name='orders_customer_id_fkey'),
    sa.PrimaryKeyConstraint('order_id', 'item_no', name='orders_pkey')
    )
    op.create_table('auth_user_user_permissions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm', initially='DEFERRED', deferrable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='auth_user_user_permissions_pkey'),
    sa.UniqueConstraint('user_id', 'permission_id', name='auth_user_user_permissions_user_id_permission_id_14a6b632_uniq')
    )
    op.create_index('auth_user_user_permissions_user_id_a95ead1b', 'auth_user_user_permissions', ['user_id'], unique=False)
    op.create_index('auth_user_user_permissions_permission_id_1fbb5f2c', 'auth_user_user_permissions', ['permission_id'], unique=False)
    op.create_table('blogging_app_comment',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('author_Comment', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blogging_app_post.id'], name='blogging_app_comment_post_id_72223a2d_fk_blogging_app_post_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('id', name='blogging_app_comment_pkey')
    )
    op.create_index('blogging_app_comment_post_id_72223a2d', 'blogging_app_comment', ['post_id'], unique=False)
    op.create_table('django_content_type',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('app_label', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='django_content_type_pkey'),
    sa.UniqueConstraint('app_label', 'model', name='django_content_type_app_label_model_76bd3d3b_uniq')
    )
    op.create_table('auth_group',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='auth_group_pkey'),
    sa.UniqueConstraint('name', name='auth_group_name_key')
    )
    op.create_index('auth_group_name_a6ea08ec_like', 'auth_group', ['name'], unique=False)
    op.create_table('authtoken_token',
    sa.Column('key', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='authtoken_token_user_id_35299eff_fk_auth_user_id', initially='DEFERRED', deferrable=True),
    sa.PrimaryKeyConstraint('key', name='authtoken_token_pkey'),
    sa.UniqueConstraint('user_id', name='authtoken_token_user_id_key')
    )
    op.create_index('authtoken_token_key_10f0b77e_like', 'authtoken_token', ['key'], unique=False)
    # ### end Alembic commands ###
